from __future__ import annotations

from typing import Protocol


class AudioPlayerProtocol(Protocol):
    def play(self, path: str, block: bool = False) -> None: ...
    def stop(self) -> None: ...
    def pause(self) -> None: ...
    def resume(self) -> None: ...
    def seek(self, position: float) -> None: ...
    def is_playing(self) -> bool: ...
    def get_position(self) -> float: ...
    def get_duration(self) -> int: ...
    def has_reached_end(self) -> bool: ...
    def current_source_name(self) -> str | None: ...
